security:
    encoders:
        App\Shared\Domain\Security\UserCredentials:
            algorithm: auto
    providers:
        dbal_provider:
            id: App\Shared\Infrastructure\DoctrineDbal\DbalUserCredentialRepository

    role_hierarchy:
        ROLE_COMPETITION_GROUP: [ROLE_USER, ROLE_ALLOWED_TO_SWITCH]
        ROLE_ADMIN:             [ROLE_USER, ROLE_ALLOWED_TO_SWITCH]

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            provider: dbal_provider
            anonymous:  true
            guard:
                authenticators:
                    - App\Shared\Domain\Security\LoginFormAuthenticator
            switch_user: true
            logout:
                path: logout
                target: /inloggen

            remember_me:
                secret:      "%secret%"
                lifetime: 2419200 # 4 weeks in seconds
                path:     /
