twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        # the value is the service's id
        calendarItems: '@App\Infrastructure\DoctrineDbal\DbalCompactCalendarItemRepository'
        header: '@App\Domain\HeaderLocation'
        competitionGroups: '@App\Infrastructure\DoctrineDbal\DbalCompetitionGroupRepository'
