twig:
  paths:
    'templates': ~
    'src/PublicInformation/Application/Templates': 'PublicInformation'
    'src/CompetitionGroup/Application/Templates': 'CompetitionGroup'
    'src/Shared/Application/Templates': 'Shared'
    'src/Subscription/Application/Templates': 'Subscription'
  form_themes: ['bootstrap_4_layout.html.twig']
  globals:
    # the value is the service's id
    calendarItems: '@App\PublicInformation\Infrastructure\DoctrineDbal\DbalCalendarItemRepository'
    competitionGroupMenuItems: '@App\PublicInformation\Infrastructure\DoctrineDbal\DbalCompetitionGroupRepository'
