twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_4_layout.html.twig']
    globals:
        # the value is the service's id
        calendarItems: '@App\Infrastructure\DoctrineDbal\DbalPublicCalendarItemRepository'
        header: '@App\Domain\HeaderLocation'
        competitionGroups: '@App\Infrastructure\DoctrineDbal\DbalCompetitionGroupRepository'
