twig:
  paths:
    'src/PublicInformation/Application/Templates': 'PublicInformation'
    'src/Shared/Application/Templates': 'Shared'
  form_themes: ['bootstrap_4_layout.html.twig']
  globals:
    # the value is the service's id
    calendarItems: '@App\PublicInformation\Infrastructure\DoctrineDbal\DbalCalendarItemRepository'
