---
- name: Provision donar.markmeijerman.nl
  hosts: all
  remote_user: "{{ ssh_provision_user }}"
  become: yes

  roles:
    - f500.debian
    - install_apt_packages
    - f500.ntp
    - f500.bashrc
    - HanXHX.mysql
    - f500.nginx
    - f500.locale
    - f500.ufw
    - f500.php7
    - f500.php_composer
    - f500.vim

- name: Install mailhog for develop
  hosts: "develop"
  remote_user: "{{ ssh_provision_user }}"
  become: yes

  roles:
    - geerlingguy.mailhog

- name: Import roles per project for develop
  hosts: "develop"
  remote_user: "{{ ssh_provision_user }}"
  become: no

  tasks:
    - name: Create sessions dev dir
      file: path=/dev/shm/donargym/var/sessions/ recurse=yes group=vagrant owner=vagrant state=directory
      become: yes

    - name: Create cache dev dir
      file: path=/dev/shm/donargym/var/cache/ recurse=yes group=vagrant owner=vagrant state=directory
      become: yes

    - name: Create logs dir
      file: path=/dev/shm/donargym/var/logs/ recurse=yes group=vagrant owner=vagrant state=directory
      become: yes

    - name: Copy the parameters distfile
      command: cp /vagrant/donargym/config/packages/parameters.yaml.dist /vagrant/donargym/config/packages/parameters.yaml creates=/vagrant/donargym/config/packages/parameters.yaml

    - name: Copy the env distfile
      command: cp /vagrant/donargym/.env.dist /vagrant/donargym/.env creates=/vagrant/donargym/.env

    - name: Composer install
      command: composer install --no-interaction --prefer-source --no-scripts --working-dir=/vagrant/donargym

- name: Production roles
  hosts: "production"
  remote_user: "{{ ssh_provision_user }}"
  become: yes

#  roles:
#    - webserver
#    - geerlingguy.certbot
#    - lets_encrypt
