security:
    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt
    providers:
        db_provider:
            entity:
                class: AppBundle:User

    role_hierarchy:
        ROLE_INGELOGD:    [ROLE_USER]
        ROLE_TURNSTER:    [ROLE_INGELOGD]
        ROLE_ASSISTENT:   [ROLE_TURNSTER]
        ROLE_TRAINER:     [ROLE_ASSISTENT]
        ROLE_SELECTIE:    [ROLE_INGELOGD]
        ROLE_ADMIN:       [ROLE_INGELOGD]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_SELECTIE, ROLE_TURNSTER, ROLE_TRAINER]

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            http_basic: ~
            provider: db_provider
            anonymous:  true
            form_login:
                login_path: /login
                check_path: /login_check
                csrf_provider: security.csrf.token_manager
            logout:
                path:   /logout
                target: /







#security:
#    encoders:
#        "MySite\Bundle\Entity\User": { algorithm: sha1, encode_as_base64: false, iterations: 1 }
#
#    providers:
#        database: { entity: "MySite\Bundle\Entity\User" }
#
#    firewalls:
#        dev:
#            pattern:    ^/(_profiler|_wdt|css|js)
#            security:   false
#
#        main:
#            pattern:    ^/
#            provider:   database
#            anonymous:  true
#            # the rest of your firewall's config
#
#    access_control:
#      - { path: ^/(join)?$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
#      - { path: ^/, roles: IS_AUTHENTICATED_FULLY }