security:
    providers:
        in_memory:
            memory: ~

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~







#security:
#    encoders:
#        "MySite\Bundle\Entity\User": { algorithm: sha1, encode_as_base64: false, iterations: 1 }
#
#    providers:
#        database: { entity: "MySite\Bundle\Entity\User" }
#
#    firewalls:
#        dev:
#            pattern:    ^/(_profiler|_wdt|css|js)
#            security:   false
#
#        main:
#            pattern:    ^/
#            provider:   database
#            anonymous:  true
#            # the rest of your firewall's config
#
#    access_control:
#      - { path: ^/(join)?$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
#      - { path: ^/, roles: IS_AUTHENTICATED_FULLY }