---

project_root: "/vagrant"
ssh_provision_user: "vagrant"

bashrc_users:
  - "vagrant"

mailhog_install_dir: /opt/mailhog

## Nginx
nginx_http_params:
  client_max_body_size: "8M"
  sendfile: off # fixes issue to reload javascript files after changes
nginx_user: vagrant
nginx_group: vagrant
nginx_server_templates: "{{ nginx_server_templates_donargym }}"
nginx_www_dir: "/var/www"

# UFW
ufw_default_policy:
  - { direction: "incoming", policy: "deny" }

ufw_rules_to_create:
  - to_port: 22 # ssh
    rule: allow
  - to_port: 80 # Nginx
    rule: allow
  - to_port: 1025
    rule: allow
  - to_port: 1080
    rule: allow
  - to_port: 2222
    rule: allow
  - to_port: 2223
    rule: allow
  - to_port: 8025 # MailHog web interface
    rule: allow
  - to_port: 3306 # Database connection
    rule: allow

# PHP 7
php7_ini_directives_global:
  disable_functions:      "passthru, system, popen"
  allow_url_fopen:        1
  session.save_path:      "/dev/shm/shared/var/sessions"
  session.cookie_secure:  0
  session.gc_probability: 1
  session.gc_divisor:     1000
  session.gc_maxlifetime: 3600
  always_populate_raw_post_data: "-1"
  mail_sendmail_path:     "{{ mailhog_install_dir }}/mhsendmail"
  display_errors: "On"
  display_startup_errors: "On"
  xdebug.profiler_enable: 1
  xdebug.remote_enable: 1
  xdebug.remote_connect_back: 1
  xdebug.idekey: "PHPSTORM"
  opcache_fast_shutdown: 0
  opcache_interned_strings_buffer: 16
  opcache_max_accelerated_files: 10240
  opcache_memory_consumption: 128
  opcache_revalidate_freq: 0
  opcache_validate_timestamps: 1

php7_fpm_pool_user: vagrant
php7_fpm_pool_group: vagrant

php7_extensions:
  - xdebug
  - memcached

# MySQL
mariadb_bind_address:  "127.0.0.1"
mariadb_root_password: "root"

mariadb_databases: "{{ mariadb_databases_donargym }}"
mariadb_users: "{{ mariadb_users_donargym }}"


nginx_server_templates_donargym:
  - name: donargym
    src: "{{ inventory_dir }}/provision/templates/nginx.cfg.j2"
    ssl: off
    index: index.php
    web_root: "{{ project_root }}/donargym/public"
    domains:
      - "donargym.loc"
      - "www.donargym.loc"
    headers:
      Content-Security-Policy: "default-src 'self'; script-src 'self' 'unsafe-inline' https://code.jquery.com https://stackpath.bootstrapcdn.com https://cdn.jsdelivr.net  ; style-src 'self' 'unsafe-inline' https://stackpath.bootstrapcdn.com; font-src 'self' data:"

donargym_db_user:     'donargym'
donargym_db_password: 'donargym'

mariadb_databases_donargym:
  - 'donargym'

mariadb_users_donargym:
  - {
    name:     "{{ donargym_db_user }}",
    password: "{{ donargym_db_password }}",
    priv:     "donargym.*:ALL",
    host:     "%"
  }
