---

- name: restart sshd
  service: name="ssh" state=restarted

- name: restart nginx
  service: name=nginx state=restarted
  register: restarted_nginx
  when: not started_nginx|changed

- name: restart rsyslogd
  service: name=rsyslog state=restarted
