<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * VoedselRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VoedselRepository extends EntityRepository
{
}
